/**
 * This class is generated by jOOQ
 */
package com.bolly.jooq.tables.records;


import com.bolly.jooq.tables.Movie;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MovieRecord extends UpdatableRecordImpl<MovieRecord> implements Record10<Integer, String, String, Integer, String, Integer, String, Date, Integer, Integer> {

    private static final long serialVersionUID = 177675343;

    /**
     * Setter for <code>bolly.MOVIE.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>bolly.MOVIE.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bolly.MOVIE.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>bolly.MOVIE.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>bolly.MOVIE.online_stream_link</code>.
     */
    public void setOnlineStreamLink(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bolly.MOVIE.online_stream_link</code>.
     */
    public String getOnlineStreamLink() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bolly.MOVIE.rating</code>.
     */
    public void setRating(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>bolly.MOVIE.rating</code>.
     */
    public Integer getRating() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>bolly.MOVIE.review</code>.
     */
    public void setReview(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>bolly.MOVIE.review</code>.
     */
    public String getReview() {
        return (String) get(4);
    }

    /**
     * Setter for <code>bolly.MOVIE.director_id</code>.
     */
    public void setDirectorId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>bolly.MOVIE.director_id</code>.
     */
    public Integer getDirectorId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>bolly.MOVIE.writer</code>.
     */
    public void setWriter(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>bolly.MOVIE.writer</code>.
     */
    public String getWriter() {
        return (String) get(6);
    }

    /**
     * Setter for <code>bolly.MOVIE.release_date</code>.
     */
    public void setReleaseDate(Date value) {
        set(7, value);
    }

    /**
     * Getter for <code>bolly.MOVIE.release_date</code>.
     */
    public Date getReleaseDate() {
        return (Date) get(7);
    }

    /**
     * Setter for <code>bolly.MOVIE.release_year</code>.
     */
    public void setReleaseYear(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>bolly.MOVIE.release_year</code>.
     */
    public Integer getReleaseYear() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>bolly.MOVIE.release_decade</code>.
     */
    public void setReleaseDecade(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>bolly.MOVIE.release_decade</code>.
     */
    public Integer getReleaseDecade() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, Integer, String, Integer, String, Date, Integer, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, Integer, String, Integer, String, Date, Integer, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Movie.MOVIE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Movie.MOVIE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Movie.MOVIE.ONLINE_STREAM_LINK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Movie.MOVIE.RATING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Movie.MOVIE.REVIEW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Movie.MOVIE.DIRECTOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Movie.MOVIE.WRITER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field8() {
        return Movie.MOVIE.RELEASE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Movie.MOVIE.RELEASE_YEAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return Movie.MOVIE.RELEASE_DECADE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOnlineStreamLink();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getRating();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getReview();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getDirectorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getWriter();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value8() {
        return getReleaseDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getReleaseYear();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getReleaseDecade();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovieRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovieRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovieRecord value3(String value) {
        setOnlineStreamLink(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovieRecord value4(Integer value) {
        setRating(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovieRecord value5(String value) {
        setReview(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovieRecord value6(Integer value) {
        setDirectorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovieRecord value7(String value) {
        setWriter(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovieRecord value8(Date value) {
        setReleaseDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovieRecord value9(Integer value) {
        setReleaseYear(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovieRecord value10(Integer value) {
        setReleaseDecade(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovieRecord values(Integer value1, String value2, String value3, Integer value4, String value5, Integer value6, String value7, Date value8, Integer value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MovieRecord
     */
    public MovieRecord() {
        super(Movie.MOVIE);
    }

    /**
     * Create a detached, initialised MovieRecord
     */
    public MovieRecord(Integer id, String name, String onlineStreamLink, Integer rating, String review, Integer directorId, String writer, Date releaseDate, Integer releaseYear, Integer releaseDecade) {
        super(Movie.MOVIE);

        set(0, id);
        set(1, name);
        set(2, onlineStreamLink);
        set(3, rating);
        set(4, review);
        set(5, directorId);
        set(6, writer);
        set(7, releaseDate);
        set(8, releaseYear);
        set(9, releaseDecade);
    }
}
