/**
 * This class is generated by jOOQ
 */
package com.bolly.jooq.tables.records;


import com.bolly.jooq.tables.MovieType;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MovieTypeRecord extends TableRecordImpl<MovieTypeRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 639676162;

    /**
     * Setter for <code>bolly.MOVIE_TYPE.movie_id</code>.
     */
    public void setMovieId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>bolly.MOVIE_TYPE.movie_id</code>.
     */
    public Integer getMovieId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bolly.MOVIE_TYPE.type_id</code>.
     */
    public void setTypeId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>bolly.MOVIE_TYPE.type_id</code>.
     */
    public Integer getTypeId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MovieType.MOVIE_TYPE.MOVIE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return MovieType.MOVIE_TYPE.TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getMovieId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovieTypeRecord value1(Integer value) {
        setMovieId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovieTypeRecord value2(Integer value) {
        setTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovieTypeRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MovieTypeRecord
     */
    public MovieTypeRecord() {
        super(MovieType.MOVIE_TYPE);
    }

    /**
     * Create a detached, initialised MovieTypeRecord
     */
    public MovieTypeRecord(Integer movieId, Integer typeId) {
        super(MovieType.MOVIE_TYPE);

        set(0, movieId);
        set(1, typeId);
    }
}
