/**
 * This class is generated by jOOQ
 */
package com.bolly.jooq.tables.records;


import com.bolly.jooq.tables.MovieActor;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MovieActorRecord extends TableRecordImpl<MovieActorRecord> implements Record2<Integer, Short> {

    private static final long serialVersionUID = -869925061;

    /**
     * Setter for <code>bolly.MOVIE_ACTOR.movie_id</code>.
     */
    public void setMovieId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>bolly.MOVIE_ACTOR.movie_id</code>.
     */
    public Integer getMovieId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bolly.MOVIE_ACTOR.actor_id</code>.
     */
    public void setActorId(Short value) {
        set(1, value);
    }

    /**
     * Getter for <code>bolly.MOVIE_ACTOR.actor_id</code>.
     */
    public Short getActorId() {
        return (Short) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Short> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Short> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MovieActor.MOVIE_ACTOR.MOVIE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field2() {
        return MovieActor.MOVIE_ACTOR.ACTOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getMovieId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value2() {
        return getActorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovieActorRecord value1(Integer value) {
        setMovieId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovieActorRecord value2(Short value) {
        setActorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovieActorRecord values(Integer value1, Short value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MovieActorRecord
     */
    public MovieActorRecord() {
        super(MovieActor.MOVIE_ACTOR);
    }

    /**
     * Create a detached, initialised MovieActorRecord
     */
    public MovieActorRecord(Integer movieId, Short actorId) {
        super(MovieActor.MOVIE_ACTOR);

        set(0, movieId);
        set(1, actorId);
    }
}
