/**
 * This class is generated by jOOQ
 */
package com.bolly.jooq;


import com.bolly.jooq.tables.Actor;
import com.bolly.jooq.tables.Director;
import com.bolly.jooq.tables.Movie;
import com.bolly.jooq.tables.MovieActor;
import com.bolly.jooq.tables.MovieType;
import com.bolly.jooq.tables.Type;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in bolly
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>bolly.ACTOR</code>.
     */
    public static final Actor ACTOR = com.bolly.jooq.tables.Actor.ACTOR;

    /**
     * The table <code>bolly.DIRECTOR</code>.
     */
    public static final Director DIRECTOR = com.bolly.jooq.tables.Director.DIRECTOR;

    /**
     * The table <code>bolly.MOVIE</code>.
     */
    public static final Movie MOVIE = com.bolly.jooq.tables.Movie.MOVIE;

    /**
     * The table <code>bolly.MOVIE_ACTOR</code>.
     */
    public static final MovieActor MOVIE_ACTOR = com.bolly.jooq.tables.MovieActor.MOVIE_ACTOR;

    /**
     * The table <code>bolly.MOVIE_TYPE</code>.
     */
    public static final MovieType MOVIE_TYPE = com.bolly.jooq.tables.MovieType.MOVIE_TYPE;

    /**
     * The table <code>bolly.TYPE</code>.
     */
    public static final Type TYPE = com.bolly.jooq.tables.Type.TYPE;
}
