/**
 * This class is generated by jOOQ
 */
package com.bolly.jooq.tables;


import com.bolly.jooq.Bolly;
import com.bolly.jooq.Keys;
import com.bolly.jooq.tables.records.TypeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Type extends TableImpl<TypeRecord> {

    private static final long serialVersionUID = -1377964594;

    /**
     * The reference instance of <code>bolly.TYPE</code>
     */
    public static final Type TYPE = new Type();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TypeRecord> getRecordType() {
        return TypeRecord.class;
    }

    /**
     * The column <code>bolly.TYPE.id</code>.
     */
    public final TableField<TypeRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>bolly.TYPE.type_name</code>.
     */
    public final TableField<TypeRecord, String> TYPE_NAME = createField("type_name", org.jooq.impl.SQLDataType.VARCHAR.length(16).nullable(false), this, "");

    /**
     * Create a <code>bolly.TYPE</code> table reference
     */
    public Type() {
        this("TYPE", null);
    }

    /**
     * Create an aliased <code>bolly.TYPE</code> table reference
     */
    public Type(String alias) {
        this(alias, TYPE);
    }

    private Type(String alias, Table<TypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private Type(String alias, Table<TypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Bolly.BOLLY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TypeRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TypeRecord> getPrimaryKey() {
        return Keys.KEY_TYPE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TypeRecord>> getKeys() {
        return Arrays.<UniqueKey<TypeRecord>>asList(Keys.KEY_TYPE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Type as(String alias) {
        return new Type(alias, this);
    }

    /**
     * Rename this table
     */
    public Type rename(String name) {
        return new Type(name, null);
    }
}
